import Foundation
import Testing
import WalletCore
@testable import Aperture

struct BitcoinImportBackupTests {
    struct Fixture: Decodable {
        let name: String
        let addresses: [String]
        let change: String
        let password: String
    }
    // Generated by Bitcoin Core 28.3 on mainnet with all networking disabled.
    // These are deliberately public fixture wallets and must never receive funds.
    private func data(_ name: String) throws -> Data {
        let url = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appendingPathComponent("Fixtures/BitcoinImport/" + name)
        return try Data(contentsOf: url)
    }

    @Test(arguments: ["descriptor-clear", "descriptor-encrypted", "legacy-clear", "legacy-encrypted"])
    func restoresEveryCoreGeneratedAddress(name: String) throws {
        let fixtures = try JSONDecoder().decode([Fixture].self, from: data("manifest.json"))
        let fixture = try #require(fixtures.first { $0.name == name })
        let material = try BitcoinCoreBackupImporter.parse(data(name + ".dat"), password: fixture.password)
        var addresses = Set<String>()
        for (id, source) in material.sources.enumerated() {
            for branch in 0..<source.descriptor.branchCount {
                for index in source.rangeStart..<min(source.rangeEnd, source.rangeStart + 10) {
                    let address = try source.descriptor.address(branch: branch, index: index, sourceID: String(id))
                    addresses.insert(address.address)
                    let key = try material.privateKey(path: address.derivationPath)
                    #expect(PrivateKey(data: key)?.getPublicKeySecp256k1(compressed: source.descriptor.compressed).data == address.publicKey)
                }
            }
        }
        #expect(Set(fixture.addresses + [fixture.change]).isSubset(of: addresses))
        #expect(try BitcoinImportedWalletMaterial.decode(material.encoded()) == material)
    }

    @Test(arguments: ["descriptor-encrypted", "legacy-encrypted"])
    func encryptedBackupRequiresCorrectPassword(name: String) throws {
        let backup = try data(name + ".dat")
        #expect(throws: BitcoinImportError.passwordRequired) { try BitcoinCoreBackupImporter.parse(backup) }
        #expect(throws: BitcoinImportError.incorrectPassword) { try BitcoinCoreBackupImporter.parse(backup, password: "wrong") }
    }

    @Test(arguments: ["descriptor-clear", "legacy-clear"])
    func rejectsTruncationAndDamagedHeaders(name: String) throws {
        let backup = try data(name + ".dat")
        for length in [0, 12, 100, 511, backup.count - 1, backup.count / 2] {
            #expect(throws: (any Error).self) { try BitcoinCoreBackupImporter.parse(Data(backup.prefix(length))) }
        }
        var damaged = backup
        damaged[12] ^= 0xff
        #expect(throws: (any Error).self) { try BitcoinCoreBackupImporter.parse(damaged) }
    }

    @Test
    func electrumPrefixesKeepScriptAndMiniKeysKeepCompression() throws {
        let wif = Base58.encode(data: Data([0x80]) + Data(repeating: 0, count: 31) + Data([1, 1]))
        let expected = [
            "p2pkh": "1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH",
            "p2wpkh": "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4",
            "p2wpkh-p2sh": "3JvL6Ymt8MVWiCNHC7oWU6nLeHNJKLZGLN",
        ]
        for (prefix, address) in expected {
            #expect(try BitcoinImportKeyEncoding.electrumDescriptor(prefix + ":" + wif).address().address == address)
        }
        let mini = try BitcoinImportKeyEncoding.mini("S6c56bnXQiBjk9mqSYE7ykVQ7NzrRy")
        #expect(!mini.compressed)
        let descriptor = try BitcoinPrivateDescriptor("pkh(\(BitcoinImportKeyEncoding.encode(mini)))")
        #expect(try descriptor.address().address == "1CciesT23BNionJeXrbxmjc7ywfiyM4oLW")
        #expect(throws: BitcoinImportError.invalidKey) { try BitcoinImportKeyEncoding.mini("S6c56bnXQiBjk9mqSYE7ykVQ7NzrRz") }
    }

    @Test
    func verifiesChecksumsAndRejectsUnsupportedPolicies() throws {
        #expect(try BitcoinDescriptorChecksum.checksum("raw(deadbeef)") == "89f8spxm")
        #expect(throws: BitcoinImportError.checksumMismatch) {
            try BitcoinPrivateDescriptor("wpkh(bad)#00000000")
        }
        #expect(throws: BitcoinImportError.unsupportedScript) { try BitcoinPrivateDescriptor("wsh(multi(2,a,b))") }
    }
}
